/**
 * Headline-artist carousel content — the single source for every slide.
 *
 * Each entry drives one complete artwork: photograph, artist name, supporting line
 * and the Castle Lite Unlocks logo variant. The overlay itself is built in
 * components/ArtistCarousel.tsx from the art direction in "00 - Assets/Plate Style.png";
 * nothing here is baked into the photography.
 *
 * Photography is generated by `python3 scripts/build-assets.py artists` into
 * /public/artists as `<image>-<width>.avif|webp`.
 */
import type { Str } from '../i18n/strings'

/** Must match ARTIST_WIDTHS in scripts/build-assets.py. */
export const ARTIST_WIDTHS = [480, 768, 1024, 1440] as const

/** Which supplied Unlocks lockup sits top-right: unlocks-blue.svg or unlocks-white.svg. */
export type LogoVariant = 'blue' | 'white'

export interface ArtistSlide {
  id: string
  /** Rendered uppercase by CSS; kept in natural case so screen readers say it as a name. */
  name: string
  /** Supporting line. Rendered uppercase by CSS. "Live in Mwanza" stays English in both locales. */
  copy: Str
  /** File stem in /public/artists. */
  image: string
  alt: Str
  /**
   * Chosen per photograph for legibility: Jolt Blue over a light top-right corner,
   * white over a blue one.
   */
  logoVariant: LogoVariant
  /**
   * object-position per composition. The sources are square, so a landscape tile only
   * crops vertically (the Y value matters) and a portrait tile only crops horizontally
   * (the X value matters).
   *   mobile  — hero stacked, 4:5 portrait tile (< 720px). The only crop today.
   *   tablet  — hero two-column, square tile (720–1023px)
   *   desktop — hero two-column, square tile (≥ 1024px)
   * Square tiles show the whole frame, so tablet/desktop only take effect if those
   * tiles are ever given another shape.
   */
  focal: { mobile: string; tablet: string; desktop: string }
  /** Ground colour behind the photo while it decodes, sampled from the photograph. */
  tone: string
  /** Centre of the face as fractions of the photo, for the round avatars on the lineup cards. */
  face: [number, number]
}

export const artists: ArtistSlide[] = [
  {
    id: 'harmonize',
    name: 'Harmonize',
    copy: { en: 'Live in Mwanza', sw: 'Live in Mwanza' },
    image: 'harmonize',
    alt: {
      en: 'Harmonize, dressed in white, seated and holding a bottle of Castle Lite',
      sw: 'Harmonize akiwa amevaa nguo nyeupe, ameketi na ameshika chupa ya Castle Lite',
    },
    logoVariant: 'blue',
    focal: { mobile: '50% 0%', tablet: '48% 0%', desktop: '50% 12%' },
    tone: '#e9e7e3',
    face: [0.41, 0.28],
  },
  {
    id: 'scotts-maphuma',
    name: 'Scotts Maphuma',
    copy: { en: 'Live in Mwanza', sw: 'Live in Mwanza' },
    image: 'scotts-maphuma',
    alt: {
      en: 'Scotts Maphuma in a white suit, reclining in a dark leather chair',
      sw: 'Scotts Maphuma akiwa amevaa suti nyeupe, ameegemea kwenye kiti cha ngozi',
    },
    logoVariant: 'blue',
    focal: { mobile: '100% 0%', tablet: '100% 0%', desktop: '50% 2%' },
    tone: '#b8cfe6',
    face: [0.67, 0.25],
  },
  {
    id: 'darassa',
    name: 'Darassa',
    copy: { en: 'Live in Mwanza', sw: 'Live in Mwanza' },
    image: 'darassa',
    alt: {
      en: 'Darassa in a white double-breasted suit, standing beside a studio microphone',
      sw: 'Darassa akiwa amevaa suti nyeupe, amesimama karibu na kipaza sauti',
    },
    logoVariant: 'white',
    focal: { mobile: '38% 0%', tablet: '36% 0%', desktop: '50% 4%' },
    tone: '#5f93cf',
    face: [0.42, 0.17],
  },
]
